### ISSUE TITLE
JSON interop?

### ISSUE THREAD

**Issue by mpizenberg** [dwayne/elm-natural#1]
Hi, I'm dealing with big integers and your package seems to fit well with some of my needs for handling unbounded integers with exact computations, instead of approximate for anything > 2^53.

Another common use-case I have is dealing with big integers in JSON files I may receive or send. JSON has no issue with big integers (contrary to JS) so it's common in tools I interact with to have integers > 2^53 in JSON, that are encoded as integers, and not as strings. I was wondering if you encountered similar use cases, and your general thoughts about JSON interop for elm-natural.

**Comment by dwayne** [comment]
> JSON has no issue with big integers (contrary to JS) so it's common in tools I interact with to have integers > 2^53 in JSON, that are encoded as integers, and not as strings.

Interesting, I didn't realize that. The spec confirms it as well:

> The goal of this specification is only to define the syntax of valid JSON texts. Its intent is not to provide any
semantics or interpretation of text conforming to that syntax. It also intentionally does not define how a valid
JSON text might be internalized into the data structures of a programming language. There are many possible
semantics that could be applied to the JSON syntax and many ways that a JSON text can be processed or
mapped by a programming language.

However, Elm's current runtime is implemented in JavaScript and as such it uses `JSON.parse` [under the hood](https://github.com/elm/json/blob/1.1.3/src/Elm/Kernel/Json.js#L188) as a first step when doing its JSON decoding.

Take a look at what happens with the following example:

```js
JSON.parse("{ \"value\" : 9223372036854775807 }")
> Object { value: 9223372036854776000 }
```

It's valid JSON so no syntax errors as per the spec but the number has to be represented in JavaScript prior to Elm getting hold of it and as a result precision is lost.

One way around it would be to preprocess the JSON to convert `{ value: 9223372036854775807 }` into `{ value: "9223372036854775807" }` and then define an Elm decoder to parse it into a `Natural`. For an example, you can [check out this Ellie](https://ellie-app.com/pvKxTnZsFn2a1).

Does that help you?

**Comment by mpizenberg** [comment]
Indeed I was thinking of going a similar route and was wondering if you did the same. In my case, interaction with these JSON objects is done via a port, where I control the JS side anyway. So I can preprocess these to apply a transformation such as converting to a string.

**Comment by dwayne** [comment]
That sounds like the easiest option. There's also the possibility of writing a JSON parser in pure Elm and then you get to control the semantics of `number`.

**Comment by dwayne** [comment]
That sounds like the easiest option. There's also the possibility of writing a JSON parser in pure Elm and then you get to control the semantics of `number`.
