### ISSUE TITLE
Add `toBase` and `fromBase` functions

### ISSUE THREAD

**Issue by Jcparkyn** [dwayne/elm-natural#3]
The library currently has a few functions for converting to strings in different bases. It would be nice to have a more general function for converting to a `List Int` in an arbitrary base (up to 2^26).

My specific use case is converting a `Natural` to `Bytes` (in a compact way) and back again, so:
- It'd be nice if 2^n bases could be optimised using bit shifts instead of divisions.
- I only need one specific base (256), but it'd be nice to have a general function to do it for all bases.
- Specific functions for working directly with `Bytes` would be nice, but probably not worth the extra dependency. 

## Proposed functions

```elm
{-| Create the natural number that represents the given list of base-`b` digits.
-}
fromBase : Int -> List Int -> Natural
fromBase b digits =
    Debug.todo ""


{-| Convert the given natural number to a list of digits in base-`b`.
-}
toBase : Int -> Natural -> List Int
toBase b n =
    Debug.todo ""
```

These could perhaps be named `toBaseBDigits` and `fromBaseBDigits` for better consistency with the string functions.

**Comment by dwayne** [comment]
@Jcparkyn Thanks for the suggestions. I've added it to the backlog, i.e. adding `toBaseBDigits` and `fromBaseBDigits`. However, I will not add any specific functions for working directly with `Bytes`.
